### PR TITLE
Read events without messages/message templates

### LINKED ISSUE #13: Read events without `@m` or `@mt`
The reader requires one of either `@m` or `@mt` to be present:

https://github.com/serilog/serilog-formatting-compact-reader/blob/dev/src/Serilog.Formatting.Compact.Reader/LogEventReader.cs#L121

But, the format allows both to be omitted:

https://github.com/serilog/serilog-formatting-compact#format-details

The original goal of this package was to round-trip Serilog events, and so this situation does not normally occur, but there's no real reason to prohibit it.

When reading such an event back into a `LogEvent`, we might choose to set the message/template to `""` (or `MessageTemplate.Empty`).

### PR DESCRIPTION
**Pull request by nblumhardt**
Fixes #13

### CODE REVIEW

**Comment by nblumhardt** [comment]
Not sure what's going on with the build here, will have to come back to it :-(

**Comment by adamchester** [comment]
Looks like you’re trying to use `netcoreapp2.0` while still using the older tooling/sdk. Upgraded tooling should fix it.

**Comment by nblumhardt** [comment]
Aargh! Missed the appveyor.yml - thanks Adam :-D 👍

**Comment by nblumhardt** [comment]
Hmm next it'll be Build.ps1 - updating that, too......

**Comment by nblumhardt** [comment]
:+1: :+1:

**Pull request merged**
